version: '3.1'

services:
  db_notes:
    container_name: db_notes
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    image: mongo:5.0.25
    command: mongod --port ${MONGO_INITDB_PORT}
    volumes:
       - db_notes_vol:/data/db
    networks:
      - server_net
  
  redis_notes:
    container_name: redis_notes
    image: redis:7.2.4
    command: --port ${REDIS_PORT}
    volumes:
      - redis-data:/data
    networks:
      - server_net
    
  notes:
    container_name: notes
    build: ./notes
    depends_on:
      - db_notes
      - redis_notes
    networks:
      - server_net
    environment:
      NOTES_PORT: ${NOTES_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_INITDB_HOST: ${MONGO_INITDB_HOST}
      MONGO_INITDB_PORT: ${MONGO_INITDB_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  db_auth:
    container_name: db_auth
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:15-alpine
    command:
      - 'postgres'
      - '-c'
      - 'port=${POSTGRES_PORT}'
    volumes:
      - db_auth_vol:/var/lib/postgresql/data
    networks:
      - server_net
    
  auth:
    container_name: auth
    build: ./auth
    depends_on:
      - db_auth
    networks:
      - server_net
    environment:
      AUTH_PORT: ${AUTH_PORT}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USE_SSL: ${POSTGRES_USE_SSL}
  
  nginx:
    restart: on-failure
    container_name: nginx
    image: nginx:1.25.4-alpine
    networks:
      - server_net
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - auth
      - notes
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_notes_vol: {}
  redis-data: {}
  db_auth_vol: {}

networks:
  server_net:
    driver: bridge
